#!/bin/bash
#SBATCH --job-name=compare
#SBATCH --output=slurm_out_weak/out.%a.out
#SBATCH --time=7-0
#SBATCH --mem=30G
#SBATCH --cpus-per-task=1
#SBATCH --array=0-4149
arrayNum="${SLURM_ARRAY_TASK_ID}"
source ../.venv/bin/activate
python compare.py --weak attack $arrayNum
